language: java
jdk:
  - oraclejdk8
before_install:
  - openssl aes-256-cbc -K $encrypted_37bd821dd0a3_key -iv $encrypted_37bd821dd0a3_iv
    -in travis/id_rsa.enc -out travis/id_rsa -d
deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: public
